server:
  port: 8080

spring:
  application:
    name: rococo-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

grpc:
  client:
    userdataClient:
      address: 'static://localhost:8092'
      negotiationType: PLAINTEXT
    artistClient:
      address: 'static://localhost:8094'
      negotiationType: PLAINTEXT
    geoClient:
      address: 'static://localhost:8096'
      negotiationType: PLAINTEXT
    museumClient:
      address: 'static://localhost:8098'
      negotiationType: PLAINTEXT
    paintingClient:
      address: 'static://localhost:8100'
      negotiationType: PLAINTEXT

rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-userdata:
  base-uri: 'http://127.0.0.1:8091'
rococo-artist:
  base-uri: 'http://127.0.0.1:8093'
rococo-geo:
  base-uri: 'http://127.0.0.1:8095'
rococo-museum:
  base-uri: 'http://127.0.0.1:8097'
rococo-painting:
  base-uri: 'http://127.0.0.1:8099'

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8080'

