create extension if not exists "uuid-ossp";

create table if not exists "country"
(
    id   UUID unique        not null default uuid_generate_v1(),
    name varchar(50) unique not null,
    primary key (id)
);

alter table "country"
    owner to postgres;

DELETE
FROM "country";

INSERT INTO "country" (name)
VALUES ('Fiji'),
       ('Tanzania'),
       ('Western Sahara'),
       ('Canada'),
       ('United States'),
       ('Kazakhstan'),
       ('Uzbekistan'),
       ('Papua New Guinea'),
       ('Indonesia'),
       ('Argentina'),
       ('Chile'),
       ('Democratic Republic of the Congo'),
       ('Somalia'),
       ('Kenya'),
       ('Sudan'),
       ('Chad'),
       ('Haiti'),
       ('Dominican Republic'),
       ('Russia'),
       ('Bahamas'),
       ('Falkland Islands'),
       ('Norway'),
       ('Greenland'),
       ('Timor-Leste'),
       ('South Africa'),
       ('Lesotho'),
       ('Mexico'),
       ('Uruguay'),
       ('Brazil'),
       ('Bolivia'),
       ('Peru'),
       ('Colombia'),
       ('Panama'),
       ('Costa Rica'),
       ('Nicaragua'),
       ('Honduras'),
       ('El Salvador'),
       ('Guatemala'),
       ('Belize'),
       ('Venezuela'),
       ('Guyana'),
       ('Suriname'),
       ('France'),
       ('Ecuador'),
       ('Puerto Rico'),
       ('Jamaica'),
       ('Cuba'),
       ('Zimbabwe'),
       ('Botswana'),
       ('Namibia'),
       ('Senegal'),
       ('Mali'),
       ('Mauritania'),
       ('Benin'),
       ('Niger'),
       ('Nigeria'),
       ('Cameroon'),
       ('Togo'),
       ('Ghana'),
       ('Guinea'),
       ('Guinea-Bissau'),
       ('Liberia'),
       ('Sierra Leone'),
       ('Burkina Faso'),
       ('Central African Republic'),
       ('Republic of the Congo'),
       ('Gabon'),
       ('Equatorial Guinea'),
       ('Zambia'),
       ('Malawi'),
       ('Mozambique'),
       ('Eswatini'),
       ('Angola'),
       ('Burundi'),
       ('Israel'),
       ('Lebanon'),
       ('Madagascar'),
       ('Palestine'),
       ('The Gambia'),
       ('Tunisia'),
       ('Algeria'),
       ('Jordan'),
       ('United Arab Emirates'),
       ('Qatar'),
       ('Kuwait'),
       ('Iraq'),
       ('Oman'),
       ('Vanuatu'),
       ('Cambodia'),
       ('Thailand'),
       ('Lao PDR'),
       ('Myanmar'),
       ('Vietnam'),
       ('Dem. Rep. Korea'),
       ('Republic of Korea'),
       ('Mongolia'),
       ('India'),
       ('Bangladesh'),
       ('Bhutan'),
       ('Nepal'),
       ('Pakistan'),
       ('Afghanistan'),
       ('Tajikistan'),
       ('Kyrgyzstan'),
       ('Turkmenistan'),
       ('Iran'),
       ('Syria'),
       ('Armenia'),
       ('Sweden'),
       ('Belarus'),
       ('Ukraine'),
       ('Poland'),
       ('Austria'),
       ('Hungary'),
       ('Moldova'),
       ('Romania'),
       ('Lithuania'),
       ('Latvia'),
       ('Estonia'),
       ('Germany'),
       ('Bulgaria'),
       ('Greece'),
       ('Turkey'),
       ('Albania'),
       ('Croatia'),
       ('Switzerland'),
       ('Luxembourg'),
       ('Belgium'),
       ('Netherlands'),
       ('Portugal'),
       ('Spain'),
       ('Ireland'),
       ('New Caledonia'),
       ('Solomon Islands'),
       ('New Zealand'),
       ('Australia'),
       ('Sri Lanka'),
       ('China'),
       ('Taiwan'),
       ('Italy'),
       ('Denmark'),
       ('United Kingdom'),
       ('Iceland'),
       ('Azerbaijan'),
       ('Georgia'),
       ('Philippines'),
       ('Malaysia'),
       ('Brunei Darussalam'),
       ('Slovenia'),
       ('Finland'),
       ('Slovakia'),
       ('Czech Republic'),
       ('Eritrea'),
       ('Japan'),
       ('Paraguay'),
       ('Yemen'),
       ('Saudi Arabia'),
       ('Northern Cyprus'),
       ('Cyprus'),
       ('Morocco'),
       ('Egypt'),
       ('Libya'),
       ('Ethiopia'),
       ('Djibouti'),
       ('Somaliland'),
       ('Uganda'),
       ('Rwanda'),
       ('Bosnia and Herzegovina'),
       ('Macedonia'),
       ('Serbia'),
       ('Montenegro'),
       ('Kosovo'),
       ('Trinidad and Tobago'),
       ('South Sudan');